version: '3.9'

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  # Node API services
  api:
    build: .
    ports:
      - 5555:5000
    environment:
      PORT: 5000
      LOCAL_URI: mongodb://mongo_db:27017/ecom
      CLOUDINARY_CLOUD_NAME: university-student
      CLOUDINARY_API_KEY: 652641367849156
      CLOUDINARY_API_SECRET: 1Mtx_xr2x3HD2aMhuc_NBbpSdpQ
      JWT_SECRET: MERNSECRET
      MAIL_FROM: "darshanikaushalya7788dkd@gmail.com"
      MAIL_HOST: "smtp.mailtrap.io"
      MAIL_PORT: 2525
      MAIL_USER: "61a9c3f66a34cb"
      MAIL_PASS: "378e9934937787"
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
